insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at agra, Meet the boss of indian historical places.if you consider the top 10 historical places in india,Taj Mahal will always ranking first in the list.The tomb is the central focus of the entire complex of the Taj Mahal.The dome is nearly 35 metres (115 ft) high which is close in measurement to the length of the base, and accentuated by the cylindrical "drum" it sits on, which is approximately 7 metres (23 ft) high. The Taj Mahalˌlit. ''Crown of the Palace''),is an Islamic ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1631 by the Mughal emperor Shah Jahan (r. 1628–1658) to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.

Construction of the mausoleum was essentially completed in 1643, but work continued on other phases of the project for another 10 years. The Taj Mahal complex is believed to have been completed in its entirety in 1653 at a cost estimated at the time to be around ₹32 million, which in 2020 would be approximately ₹70 billion (about US $1 billion). The construction project employed some 20,000 artisans under the guidance of a board of architects led by the court architect to the emperor, Ustad Ahmad Lahauri. Various types of symbolism have been employed in the Taj to reflect natural beauty and divinity.

The Taj Mahal was designated as a UNESCO World Heritage Site in 1983 for being "the jewel of Muslim art in India and one of the universally admired masterpieces of the world''s heritage". It is regarded by many as the best example of Mughal architecture and a symbol of India''s rich history. The Taj Mahal attracts more than 6 million visitors a year and in 2007, it was declared a winner of the New 7 Wonders of the World (2000–2007) initiative.', 1, 'https://www.dnpindia.in/wp-content/uploads/2020/09/TSJ-MSHSL.jpg', 'Agra,India', 'https://goo.gl/maps/niuHDHemav8LpqAV9', 'Taj Mahal', 'taj-mahal');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at agra,One of the historical tourist places in India, the Red Fort was constructed over ten years from 1638 to 1648. This fort was constructed when Shah Jahan shifted the capital from Agra to Delhi and it was then known as the Qila-e-Mubarak. The fort was plundered of its artwork and jewels during Nadir Shah''s invasion of the Mughal Empire in 1739. Most of the fort''s marble structures were subsequently demolished by the British following the Indian Rebellion of 1857. The fort''s defensive walls were largely undamaged, and the fortress was subsequently used as a garrison. 
On 15 August 1947, the first Prime Minister of India, Jawaharlal Nehru, raised the Indian flag above the Lahori Gate. Every year on India''s Independence Day (15 August), the Prime Minister hoists the Indian tricolour flag at the fort''s main gate and delivers a nationally broadcast speech from its ramparts. 
The Red Fort was designated a UNESCO World Heritage Site in 2007 as part of the Red Fort Complex.', 2, 'https://wallpapercave.com/wp/wp4109816.jpg', 'Delhi,India', 'https://goo.gl/maps/WpFsr2Z8Y829QuZA9', 'Red Fort', 'red-fort');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at Delhi,Regarded as the site of the first Muslim kingdom in northern India, the Qutub Minar is definitely one of the most historical sites in India. It is one of the finest examples of Indo-Muslim architecture with its intricate red sandstone storeys.The Minar is surrounded by several historically significant monuments of the Qutb complex. Quwwat-ul-Islam Mosque, to the north-east of the Minar was built by Qutub-ud-Din Aibak in A.D. 1198. It is the earliest extant - mosque built by the Delhi Sultans. It consists of a rectangular courtyard enclosed by cloisters, erected with the carved columns and architectural members of 27 Jain and Hindu temples, which were demolished by Qutub-ud-Din Aibak as recorded in his inscription on the main eastern entrance.[16] Later, a lofty arched screen was erected, and the mosque was enlarged, by Shams-ud- Din Itutmish (A.D. 1210-35) and Ala-ud-Din Khalji. The Iron Pillar in the courtyard bears an inscription in Sanskrit in Brahmi script of fourth century A.D., according to which the pillar was set up as a Vishnudhvaja (standard of god Vishnu) on the hill known as Vishnupada in memory of a mighty king named Chandra.[16] ', 3, 'https://editorialge.com/wp-content/uploads/2020/10/Qutub-Minar-1.jpg', 'Delhi,India', 'https://goo.gl/maps/3YDfwhQty2ZyW7N48', 'Qutub Minar', 'qutub-minar');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at delhi,Humayun’s Tomb is one of the most famous and important places in India. Humayun’s wife Hamida Banu Begum commissioned the building of this tomb for her husband in the 15th century. Arched alcoves, beautiful domes, elaborate corridors and kiosks – all make this monument a grandeur of Indian architecture.La tomba di Humayun fu costruita per ordine della vedova Hamida Banu Begum a partire dal 1562 (e dunque diversi anni dopo la morte del marito) per il costo di 1,5 milioni di rupie dell''epoca[1]. Secondo ''Abd al-Qadir Bada''uni, uno dei pochi storici contemporanei alla costruzione che ne facciano menzione, l''architetto incaricato di realizzare l''edificio fu Mirak Mirza Ghiyas (talvolta indicato anche come Mirak Ghiyathuddin). Egli era di origini persiane, dato che giunse in India da Herat (attuale Afghanistan nord-occidentale) e risulta aver operato sia nella sua città d''origine che a Bukhara (attuale Uzbekistan), oltre che in varie località del subcontinente. Mirak Mirza Ghiyas morì comunque prima del completamento dell''opera e i lavori furono seguiti dal figlio di questi, Sayyed Muhammad ibn Mirak Ghiyathuddin fino al termine, nel 1571.', 4, 'https://th.bing.com/th/id/R.85861e9159be5181b5b5c4d34fd7c654?rik=9vs6PeyjoYnh%2fA&riu=http%3a%2f%2f2.bp.blogspot.com%2f-ksyphpnptOw%2fUtzzAG6cFLI%2fAAAAAAAABHI%2fA0-Gz6jmwcE%2fs1600%2fDelhi%2bHumayun%27s%2bTomb.jpg&ehk=m1SyxFjMzvinkg2PZyjWz3LYm3eEx2DWdXemQNV4RmE%3d&risl=&pid=ImgRaw&r=0', 'Delhi,India', 'https://goo.gl/maps/z1syUrcXsaSoZqe88', 'Humayun''s Tomb', 'humayun-tomb');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at Telangana,Golconda Fort is located in the western part of Hyderabad city and is about 9 km from the Hussain Sagar Lake. The outer fort occupies an area of three square kilometers, which is 4.8 kilometers in length.Golconda fort is undoubtedly one of most magnificent fortress complexes in India. The history of Golconda Fort goes back to early 13th century, when it was ruled by the Kakatiya’s followed by Qutub Shahi kings, who ruled the region in 16th and 17th century. The fortress rests on a granite hill 120 meters high while huge crenellated ramparts surround this structure.During the early seventeenth century a strong cotton-weaving industry existed in Golconda. Large quantities of cotton were produced for domestic and exports consumption. High quality plain or patterned cloth made of muslin and calico was produced. Plain cloth was available as white or brown colour, in bleached or dyed variety. Exports of this cloth was to Persia and European countries. Patterned cloth was made of prints which were made indigenously with indigo for blue, chay-root for red coloured prints and vegetable yellow. Patterned cloth exports were mainly to Java, Sumatra and other eastern countries.After 200 years, Bahmani rulers took possession of the fort. Under the Bahmani Sultanate, Golconda slowly rose to prominence. Sultan Quli Qutb-ul-Mulk (r. 1487–1543), sent by the Bahmanids as a governor at Golconda, established the city as the seat of his government around 1501. Bahmani rule gradually weakened during this period, and Sultan Quli (Quli Qutub Shah period) formally became independent in 1518, establishing the Qutb Shahi dynasty based in Golconda.[5][6] Over a period of 62 years, the mud fort was expanded by the first three Qutb Shahi sultans into the present structure, a massive fortification of granite extending around 5 km (3.1 mi) in circumference. It remained the capital of the Qutb Shahi dynasty until 1590 when the capital was shifted to Hyderabad. The Qutb Shahis expanded the fort, whose 7 km (4.3 mi) outer wall enclosed the city.', 6, 'https://th.bing.com/th/id/R.67efcb7734d2bb4f7f2401ac87868276?rik=uU%2fOZQyXe5wdtg&riu=http%3a%2f%2fwww.thesoultrails.com%2fwp-content%2fuploads%2f2018%2f11%2fGolconda-Fort-Hyderabad-Monuments-Heritage-3.jpg&ehk=Bh6YeDuKuhsp7poFXTT%2biB%2f8e3cmcl08%2bVey9wj7C%2f4%3d&risl=&pid=ImgRaw&r=0', 'Telangana,India', 'https://goo.gl/maps/KXdeUC7VRM3VH4cj8', 'Golkonda Fort', 'golkonda-fort');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at Maharastra,The Ajanta Caves are approximately 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE in the Aurangabad district of Maharashtra state in India. The paintings in the Ajanta caves predominantly narrate the Jataka tales. These are Buddhist legends describing the previous births of the Buddha.Monasteries
a monastery, or vihara, with its square hall surrounded by monks'' cells
The majority of the caves are vihara halls with symmetrical square plans. To each vihara hall are attached smaller square dormitory cells cut into the walls.A vast majority of the caves were carved in the second period, wherein a shrine or sanctuary is appended at the rear of the cave, centred on a large statue of the Buddha, along with exuberantly detailed reliefs and deities near him as well as on the pillars and walls, all carved out of the natural rock.This change reflects the shift from Hinayana to Mahāyāna Buddhism. These caves are often called monasteries. 
The Ajanta Caves constitute ancient monasteries and worship-halls of different Buddhist traditions carved into a 75-metre (246 ft) wall of rock.[8][9] The caves also present paintings depicting the past lives [10] and rebirths of the Buddha, pictorial tales from Aryasura''s Jatakamala, and rock-cut sculptures of Buddhist deities.[8][11][12] Textual records suggest that these caves served as a monsoon retreat for monks, as well as a resting site for merchants and pilgrims in ancient India.[8] While vivid colours and mural wall-painting were abundant in Indian history as evidenced by historical records, Caves 16, 17, 1 and 2 of Ajanta form the largest corpus of surviving ancient Indian wall-painting.[13] 
 
Panoramic view of Ajanta Caves from the nearby hill
The Ajanta Caves are mentioned in the memoirs of several medieval-era Chinese Buddhist travellers to India and by a Mughal-era official of Akbar era in the early 17th century.[14] They were covered by jungle until accidentally "discovered" and brought to Western attention in 1819 by a colonial British officer Captain John Smith on a tiger-hunting party.[15] The caves are in the rocky northern wall of the U-shaped gorge of the river Waghur,[16] in the Deccan plateau.[17][18] Within the gorge are a number of waterfalls, audible from outside the caves when the river is high.[19] 
With the Ellora Caves, Ajanta is one of the major tourist attractions of Maharashtra. It is about 6 kilometres (3.7 miles) from Fardapur, 59 kilometres (37 miles) from the city of Jalgaon, Maharashtra, India, 104 kilometres (65 miles) from the city of Aurangabad, and 350 kilometres (220 miles) east-northeast of Mumbai
', 7, 'https://media.cntraveller.in/wp-content/uploads/2017/05/9-Ajanta.jpg', 'Maharastra,India', 'https://goo.gl/maps/3tXSnPTXztpEDegN7', 'Ajanta Caves', 'ajanta-caves');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at telengana,The Charminar is a monument and mosque in Hyderabad, India. The structure was built in 1591 AD. It is the most famous building of Hyderabad and also one of the most famous buildings in India.Charminar is one of the oldest monuments in India, and it is situated in Hyderabad, Telangana. Charminar was built in 1591 and is a global symbol of Hyderabad. This monument is the official emblem of Telangana.The Charminar is situated on the east bank of Musi River.[5] To the west lies the Laad Bazaar, and to the southwest lies the richly ornamented granite Makkah Masjid.[6] It is listed as an archaeological and architectural treasure on the official list of monuments prepared by the Archaeological Survey of India.[7] The English name is a translation and combination of the Urdu words chār and minar or meenar, translating to "Four Pillars"; the eponymous towers are ornate minarets attached and supported by four grand arches.The Charminar was constructed at the intersection of the historical trade route that connects the city to international markets through the port city of Machilipatnam.[13]: 195  The Old City of Hyderabad was designed with Charminar as its centrepiece.[14] The city was spread around the Charminar in four different quadrants and chambers, segregated according to the established settlements. Towards the north of Charminar is the Char Kaman, or four gateways, constructed in the cardinal direction.[10][13][15][16]: 170  Additional eminent architects from Persia were also invited to develop the city plan. The structure itself was intended to serve as a mosque and madrasa. It is of Indo-Islamic architecture style, incorporating Persian architectural elements. A sample of Charminar is said to have been created at Dabirpura/Nagaboli graveyard before the actual construction. 
Historian Masud Hussain Khan says that the construction of Charminar was completed in the year 1592, and that it is the city of Hyderabad which was actually founded in the year 1591.[17]: 4  According to the book "Days of the Beloved", Qutb shah constructed the Charminar in the year 1589, on the very spot where he first glimpsed his future queen Bhagmati, and after her conversion to Islam, Qutb Shah renamed the city as "Hyderabad". Though the story was rejected by the historians and scholars, it became popular folklore among the locals.[18]: 3, 12  
Qutb Shah was also among the early poets of Dakhani Urdu. While laying the foundation of Charminar, he performed the prayers in Dakhini couplets, which are recorded as follows:[17]: 4 [19] 
Dakhini Urdu
میرا شہر لوگوں سے مامور کر
راكهيو جوتو دريا میں مچھلی جيسے 
Translation into Telugu
నదిలో చేపలని ఎలా నింపావో
ఈ నగరాన్ని కూడా అలా నింపు దేవుడా[17]: 4 [19]
Translation into English
Fill this city of mine with people as,
You filled the river with fishes O Lord.[17]: 4 [19]
Hunterian Transliteration
Mere shahr logon se mamoor kar,
Rakhiyo joto darya mein machhli jaise.[17]: 4 [19]
Translation into Hindi
मेरा शहर लोगों के मामूर कर,
राख्यों जो तो दरया में मछली जैसी', 8, 'http://3.bp.blogspot.com/-KHH4bSlKcBs/Tomoh-SI00I/AAAAAAAAAU0/gtrAmnPOoy0/s1600/charminar+%25281%2529.jpg', 'Telangana,India', 'https://goo.gl/maps/ryuhpXX284NVbBc38', 'Charminar', 'charminar');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located  at karnataka,The Mysore Palace, also known as Amba Vilas Palace, is a historical palace and a royal residence (house). It is located in Mysore, Karnataka. It used to be the official residence of the Wadiyar dynasty and the seat of the Kingdom of Mysore. The palace is in the centre of Mysore, and faces the Chamundi Hills eastward.The palace facing Chamundi Hills is a manifestation of the devotion of the Maharajas of Mysore towards Goddess Chamundi. The emblem and coat of arms of the Mysore Kingdom adorns the entrance gate and arch. A large, beautiful and well-maintained garden surrounding the palace makes the site even more spectacular. The last palace, now known as the Old Palace or the Wooden Palace, burned to ashes during a wedding in 1896. Maharaja Krishnaraja Wodeyar IV and his mother Maharani Kempananjammanni Devi commissioned the British architect Henry Irwin to build a new palace.[2] E.W. Fritchley worked as a consulting Engineer. Meanwhile, the royal family stayed in the nearby Jaganmohan Palace. Construction was overseen by an executive engineer in the Mysore Palace division. He conducted elaborate architectural studies during his visits to Delhi, Madras, and Calcutta, and these were used to plan the new palace. The construction cost was placed at Rs 41,47,913 (around $30 million adjusted to inflation) and the palace was completed in 1912.[3][4] 
The palace was further expanded in around 1930 (including the addition of the present Public Durbar Hall wing) during the reign of Maharaja Jayachamarajendra Wadiyar', 9, 'http://3.bp.blogspot.com/_hEeDlsg8wA4/TT6L8hncQhI/AAAAAAAADGU/XWItBDceBBA/s1600/11hto3p.jpg', 'Karnatak,India', 'https://goo.gl/maps/qrGqT3V5a8gB7LJU6', 'Mysore Palace', 'mysore-palace');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at delhi,The India Gate (formerly known as the All India War Memorial) is a war memorial located astride the Rajpath on the eastern edge of the "ceremonial axis" of New Delhi, formerly called duty path.India Gate is one of many British monuments built by order of the Imperial War Graves Commission (later renamed Commonwealth War Graves Commission). The architect was Sir Edwin Lutyens, an Englishman who designed numerous other war memorials and was also the principal planner of New Delhi. The India Gate was part of the work of the Imperial War Graves Commission (IWGC), which came into existence in December 1918 under the British rule for building war graves and memorials to soldiers who were killed in the First World War.[3] The foundation stone of the gate then called the All India War Memorial, was laid on 10 February 1921, at 16:30, by the visiting Duke of Connaught in a ceremony attended by Officers and Men of the British Indian Army, Imperial Service Troops, the Commander in Chief, and Chelmsford, the viceroy.[4] On the occasion, the viceroy is reported to have said, "The stirring tales of individual heroism, will live forever in the annals of this country", and that the memorial which was a tribute to the memory of heroes, "known and unknown", would inspire future generations to endure hardships with similar fortitude and "no less valor".[4] The Duke also read out a message by the King, which said, "On this spot, in the central vista of the Capital of India, there will stand a Memorial Archway, designed to keep", in the thoughts of future generations, "the glorious sacrifice of the officers and men of the British Indian Army who fought and fell". During the ceremony, the Deccan Horse, 3rd Sappers and Miners, 6th Jat Light Infantry, 34th Sikh Pioneers, 39th Garhwal Rifles, 59th Scinde Rifles (Frontier Force), 117th Mahrattas, and 5th Gurkha Rifles 
Ten years after the foundation stone laying ceremony, on 12 February 1931, the memorial was inaugurated by Lord Irwin, who on occasion said "those who after us shall look upon this monument may learn in pondering its purpose something of that sacrifice and service which the names upon its walls record."', 10, 'http://www.volunteerworkindia.org/wp-content/uploads/2017/01/Indiagate-1024x681.jpg', 'Delhi,India', 'https://goo.gl/maps/v643XJVhtbb9vSeT8', 'India Gate', 'india-gate');
insert into "places" ("category", "description", "id", "image", "location", "maps_link", "name", "slug") values ('Historical', 'Located at karnataka,Hampi or Hampe, also referred to as the Group of Monuments at Hampi, is a UNESCO World Heritage Site located in east-central Karnataka, India. It is a pilgrimage centre of the Hindu religion. Hampi was the capital of the Vijayanagara Empire in the 14th century.Emperor Ashoka''s Rock Edicts in Nittur and Udegolan—both in Bellary district 269-232 BCE—suggest this region was part of the Maurya Empire during the 3rd century BCE. A Brahmi inscription and a terracotta seal dating to about the 2nd century CE have been found during site excavations.[19][20] The town is mentioned in Badami Chalukya''s inscriptions as Pampapura; dating from between the 6th and 8th centuries.[18] 
By the 10th century, it had become a centre of religious and educational activities during the rule of the Hindu kings Kalyana Chalukyas, whose inscriptions state that the kings made land grants to the Virupaksha temple.[18][21] Several inscriptions from the 11th to 13th centuries are about the Hampi site, with a mention of gifts to goddess Hampa-devi.[19] Between the 12th and 14th centuries, Hindu kings of the Hoysala Empire of South India built temples to Durga, Hampadevi and Shiva, according to an inscription dated about 1,199 CE. Hampi became the second royal residence; one of the Hoysala kings was known as Hampeya-Odeya or "lord of Hampi".[18][21] According to Burton Stein, the Hoysala-period inscriptions call Hampi by alternate names such as Virupakshapattana, Vijaya Virupakshapura in honour of the old Virupaksha (Shiva) temple there.Located in Karnataka near the modern-era city of Hosapete, Hampi''s ruins are spread over 4,100 hectares (16 sq mi) and it has been described by UNESCO as an "austere, grandiose site" of more than 1,600 surviving remains of the last great Hindu kingdom in South India that includes "forts, riverside features, royal and sacred complexes, temples, shrines, pillared halls, mandapas, memorial structures, water structures and others".[8] 
Hampi predates the Vijayanagara Empire, it is mentioned in the Ramayana and the Puranas of Hinduism as Pampaa Devi Tirtha Kshetra.[3][9] Hampi continues to be an important religious centre, housing the Virupaksha Temple, an active Adi Shankara-linked monastery and various monuments belonging to the old city', 11, 'https://img.ev.mu/images/articles/960x/843778.jpg', 'Karnataka,India', 'https://goo.gl/maps/znsR9p8dQcDJvYPd8', 'Hampi', 'hampi');
